runtime: python37
entrypoint: gunicorn -b :$PORT wishlist.wsgi

handlers:
- url: /static
  static_dir: www/static/

- url: /.*
  script: auto

env_variables:
  TRAVELER_PW: M58h62mrwe6kgzf8

beta_settings:
  cloud_sql_instances: travel-wish:us-central1:wishlist-db